# Generated by Django 6.0.2 on 2026-04-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="update",
            new_name="updated",
        ),
    ]
